### ISSUE TITLE
Save with {patch:true} should only validate the fields sent to the save

### ISSUE THREAD

**Issue by buildmaster** [bogus34/bookshelf-schema#8]
Create a schema

```
bookshelf.Model.extend({
    tableName: 'thing'
  },{
 schema: [
      new StringField('a', {
        required: true
      }),
      new StringField('b', {
        required: true
      })
    ]
})
```
then create an object in the database
```
new Thing({id:1, a:'something',b:'something'}).save()
```

now try and just update a single field the object
```
Thing.where({id:1}).save({b:'something else'},{patch:true});
```

I'd expect this to save as I'm only updating the `b` field and that's a valid value, but it fails with validation on the `a` field.

**Comment by bogus34** [comment]
should be fixed in version 0.3.0, thanks for reporting

**Comment by roackb2** [comment]
Is this fixed?  
I update to 0.3.0 but still failing when using `save` to update attributes with `{patch: true}`

**Comment by bogus34** [comment]
Yes, should be fixed and covered with a test case.
If it's not, could you provide a failing example?

**Comment by roackb2** [comment]
here is my test case
```javascript
'use strict';

import { bookshelf, knex } from 'model/core';
import { StringField } from 'bookshelf-schema/lib/fields';


class Test extends bookshelf.Model {
    get tableName() {
        return 'test';
    }
}

Test.schema([
    StringField('name', {required: true}),
    StringField('content', {required: true})
])

async function run() {
    try {
        await knex.schema.createTable('test', table => {
            table.increments('id').primary();
            table.string('name');
            table.string('content');
        })
        let test = await Test.forge({name: 'hey', content: 'yo'}).save();
        try {
            test = await test.save({name: 'hi'},{patch:true});
        } catch(err) {
            console.log('update error');
            console.log(err);
        }
        await knex.schema.dropTable('test');
        process.exit(0)
    } catch(err) {
        console.log(err)
        process.exit(0)
    }
}

run()
```
and this is what I get
```bash
update error
{ Checkit Errors - content: The content is required
    at module.exports (/usr/src/app/node_modules/checkit/core.js:479:26)
    at Object.<anonymous> (/usr/src/app/node_modules/checkit/index.js:2:35)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/bookshelf-schema/lib/index.js:32:11)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
From previous event:
    at Test.triggerThen (/usr/src/app/node_modules/bookshelf/lib/base/events.js:175:32)
    at Test.<anonymous> (/usr/src/app/node_modules/bookshelf/lib/model.js:1045:19)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at Test.<anonymous> (/usr/src/app/node_modules/bookshelf/lib/model.js:970:8)
From previous event:
    at Test.save (/usr/src/app/node_modules/bookshelf/lib/plugins/virtuals.js:158:25)
    at Test.Model.save (/usr/src/app/node_modules/bookshelf-schema/lib/index.js:251:39)
    at _callee$ (/usr/src/app/local/scripts/test_validation.js:27:31)
    at tryCatch (/usr/local/lib/node_modules/babel-cli/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/babel-cli/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/babel-cli/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/usr/src/app/local/scripts/test_validation.js:75:191)
    at /usr/src/app/local/scripts/test_validation.js:75:361
  message: '1 invalid values',
  errors:
   { content:
      { undefined:
          at module.exports (/usr/src/app/node_modules/checkit/core.js:448:24)
          at Object.<anonymous> (/usr/src/app/node_modules/checkit/index.js:2:35)
          at Module._compile (module.js:556:32)
          at Module._extensions..js (module.js:565:10)
          at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:152:7)
          at Module.load (module.js:473:32)
          at tryModuleLoad (module.js:432:12)
          at Function.Module._load (module.js:424:3)
          at Module.require (module.js:483:17)
          at require (internal/module.js:20:19)
          at Object.<anonymous> (/usr/src/app/node_modules/bookshelf-schema/lib/index.js:32:11)
          at Module._compile (module.js:556:32)
          at Module._extensions..js (module.js:565:10)
          at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:152:7)
          at Module.load (module.js:473:32)
          at tryModuleLoad (module.js:432:12)
        message: 'The content is required',
        errors: [Object],
        key: 'content' } } }
```

bookshelf-schema version 0.3.1

**Comment by roackb2** [comment]
@bogus34   I digged into the code where validation happens, and saw following:
```coffeescript
        validate: (self, attrs, options = {}) ->
            if not @constructor.__bookshelf_schema_options.validation \
            or options.validation is false
                return utils.Fulfilled()

            json = if options.patch
                attrs
            else
                @toJSON(validating: true)

            validations = @constructor.__bookshelf_schema?.validations or []
            modelValidations = @constructor.__bookshelf_schema?.modelValidations
            options = @_checkitOptions.call(this)
            checkit = CheckIt(validations, options).run(json)
            if @modelValidations and @modelValidations.length > 0
                checkit = checkit.then -> CheckIt(all: model_validations, options).run(all: json)
            checkit
```

If I didn't misunderstand,  above code did pick the attributes passed to `save` method when `{patch:true}` is set, but still applies all checking rules defined in model schema to CheckIt. perhaps adding some lines as following would fix it. Since I know not a shit about CoffeeScript, I'll give the example in JavaScript with lodash:

```javascript
 validations = options.patch ? _.pick(validations, _.keys(json)) : validations;   
```

following where the original code gets the validation, i.e.
```coffeescript
 validations = @constructor.__bookshelf_schema?.validations or []
```

I applies this change directly on the transpiled code in my node_modules folder and it passes the simple test case in the last comment.

**Comment by bogus34** [comment]
Yes, you are right. And it shoudn't run whole model validation when patching.
Just published v0.3.2
Thanks!

**Comment by cantado** [comment]
There is still an issue with the validation.
Your utils.pick method does not work with an array of field names as second argument. (but lodash.pick does)
```
var utils = require('bookshelf-schema/lib/utils')
var obj = {bar: 1, foo: 2}
utils.pluck(obj, 'bar', 'foo']) // returns {bar: 1, foo: 2}
utils.pluck(obj, ['bar', 'foo]) // returns {}
```
You have to fix the pluck call or update the pluck method to support an array as second argument.
Thanks ✌️

**Comment by bogus34** [comment]
Yeah, correct. And it had passed tests for a quite funky reason.
Thanks @cantado!
